# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vusC_U <- function(tt1, tt2, tt3) {
    .Call(`_emplikROCS_vusC_U`, tt1, tt2, tt3)
}

vusC_varEL <- function(tt1, tt2, tt3) {
    .Call(`_emplikROCS_vusC_varEL`, tt1, tt2, tt3)
}

vusC_full_core <- function(tt1, tt2, tt3) {
    .Call(`_emplikROCS_vusC_full_core`, tt1, tt2, tt3)
}

place_U <- function(tt1, tt2, tt3) {
    .Call(`_emplikROCS_place_U`, tt1, tt2, tt3)
}

vusC_ties <- function(tt1, tt2, tt3) {
    .Call(`_emplikROCS_vusC_ties`, tt1, tt2, tt3)
}

